name: Django CI

on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [staging]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: templatedb
          POSTGRES_USER: djangouser
          POSTGRES_PASSWORD: djangouser
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_SETTINGS_MODULE: ${{ vars.DJANGO_SETTINGS_MODULE }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ vars.DEBUG }}
      DATABASE_ENGINE: ${{ vars.DATABASE_ENGINE }}
      DATABASE_NAME: ${{ vars.DATABASE_NAME }}
      DATABASE_USER: ${{ vars.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ vars.DATABASE_HOST }}
      DATABASE_PORT: ${{ vars.DATABASE_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PYTHON_VERSION || '3.11' }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/development.txt
          pip install pylint

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests with pytest
        run: pytest --disable-warnings
